class MailData(object):
    """
    Mail Data,
    Mail Team Data,
    Mail SonicDTS Number,
    """
    mail_dict = {

        'Allen (Yaqiang) Nan': 'ynan@SonicWALL.com',
        'Emily (Yunzhu) Wei': 'ywei@SonicWALL.com',
        'Spring (Congli) Ye': 'coye@SonicWALL.com',
        'Kelly (Liyuan) Du': 'ldu@SonicWALL.com',
        'Sandy (Rong) Hu': 'rhu@SonicWALL.com',
        'Michelle (Xin) Ma': 'mma@SonicWALL.com',
        'Jie Lian': 'JLian@SonicWALL.com',
        'Jessie (Dan) Huang': 'dhuang@SonicWALL.com',
        'Emma  (Huihui) Xu': 'hxu@SonicWALL.com',
        'Emma (Huihui) Xu': 'hxu@SonicWALL.com',
        'Candy Chen': 'xchen@SonicWALL.com',
        'Cathy (Guimin) Zhao': 'czhao@SonicWALL.com',
        'Juanjuan Liu': 'juliu@SonicWALL.com',
        'Tracy (Juanjuan) Liu': 'juliu@SonicWALL.com',
        'Terry (Huan)  Ding': 'hding@SonicWALL.com',
        'Terry (Huan) Ding': 'hding@sonicwall.com',
        'Frank (Panjiang) Cao': 'pcao@SonicWALL.com',
        'Jun Zhang': 'JnZhang@SonicWALL.com',
        'Jack (Peining)  Zhou': 'pzhou@SonicWALL.com',
        'Jack (Peining) Zhou': 'pzhou@SonicWALL.com',
        'Alisa (Qiongling) Shi': 'qshi@SonicWALL.com',
        'Wei (Huawei) Hua': 'hhua@SonicWALL.com',
        'Bush (Yuhang) Chen': 'BYHChen@SonicWALL.com',
        'Jason (Kai) Huang': 'khuang@SonicWALL.com',
        'Caesar (Zhengrong) Ye': 'zye@SonicWALL.com',
        'Nick Zhang': 'NiZhang@SonicWALL.com',
        'XiangYun Zhou': 'XZhou@SonicWALL.com',
        'Chan Yuan': 'CYuan@SonicWALL.com',
        'Mike (Junhua) Wu': 'jwu@SonicWALL.com',
        'Mike (Junhua)  Wu': 'jwu@SonicWALL.com',
        'Xiuyun Hu': 'xhu@sonicwall.com',
        'Xuqian Yami Wang': 'xuwang@sonicwall.com',
        'Fitz Huang': 'fhuang@sonicwall.com',
        'Anna Ge': 'age@sonicwall.com',
        'Fangfang Xia': 'fxia@SonicWALL.com',
        'Jenny (Weijing) Huang': 'whuang@SonicWALL.com',
        'Judy (Yuan) Yuan': 'jyuan@SonicWALL.com',
        'Lucy Li': 'Luli@SonicWALL.com',
        'Yuling Hou': 'YHou@SonicWALL.com',
        'Rock (Rufeng) Wei': 'rwei@SonicWALL.com',
        'Shawn (Jiran) Xiong': 'JRXiong@SonicWALL.com',
        'Stephanie Li': 'yili@SonicWALL.com',
        'Victor (Jianbo) Ding': 'vding@SonicWALL.com',
        'Xiaoren Xu': 'XXu@SonicWALL.com',
        'Lin Sun': 'LSun@SonicWALL.com',
        'Mia Guo': 'MGuo@SonicWALL.com',
        'Lebin Bian': 'lbian@SonicWALL.com',
        'May (Xiaolei)  Yu': 'xyu@SonicWALL.com',
        'May (Xiaolei) Yu': 'xyu@SonicWALL.com',
        'Neil (Lei) Zhang': 'lezhang@SonicWALL.com',
        'Rosa  (RongXia) Meng': 'rmeng@SonicWALL.com',
        'Rosa (RongXia) Meng': 'rmeng@SonicWALL.com',
        'Wenlu Gong': 'wgong@SonicWALL.com',
        'Yaqian Ye': 'YYe@SonicWALL.com',
        'Chunxia Xu': 'cxu@SonicWALL.com',
        'May (Chunxia) Xu': 'cxu@SonicWALL.com',
        'Haoyuan Ma': 'HyMa@SonicWALL.com',
        'Joy Xu': 'JXu@SonicWALL.com',
        'Francis (Renbin) Lv': 'flv@sonicwall.com',
        'Chris (Feifei) Dai': 'cdai@sonicwall.com',
        'Lily (Lili) Qian': 'lqian@SonicWALL.com',
        'Bruce (Yi) Chen': 'BYChen@SonicWALL.com',
        'Shang (Rongfang) Shang': 'rshang@SonicWALL.com',
        'Si Li': 'luli@sonicwall.com',
        'Eric (Dong) Xiang': 'hding@sonicwall.com',
        'Sophie Shi': 'hding@sonicwall.com',
        'Arun Yogeesh': 'hding@sonicwall.com',
        'Tony (Yetong) Wang': 'hding@sonicwall.com',
        'Weijie (Wei Jie) Shen': 'hding@sonicwall.com',
        'Wenbo Wei': 'hding@sonicwall.com',
        "Shane O'Hanlon": 'hding@sonicwall.com',
        'Winni (Wenhua) Gu': 'hding@sonicwall.com',
        'Weily (Wei) Zhou': 'hding@sonicwall.com',
        'Zhong Chen': 'hding@sonicwall.com',
        'Saikiran Madugula': 'hding@sonicwall.com',
        'Aaron (Bo) Zhang': 'hding@sonicwall.com',
        'Narayanan Ayyenperumal': 'hding@sonicwall.com',
        'Jenny (Jie) Liu': 'hding@sonicwall.com',
        'Mallikharjun Vatti': 'hding@sonicwall.com',
        'Hui (Hui) Ling': 'hding@sonicwall.com',
        'Sam Liddicott': 'hding@sonicwall.com',
        'Freeman (Longfei) Qin': 'hding@sonicwall.com',
        'Lucia (Lulu) Wu': 'hding@sonicwall.com',
        'Jeremy (Wenfeng) Lei': 'jlei@sonicwall.com',
        'Rock (Huanxin) Dong [X] (Inactive)': 'hding@sonicwall.com',
        'Arlene Zhang [X] (Inactive)': 'hding@sonicwall.com',
        'Peter (Wenjian) Dong [X] (Inactive)': 'hding@sonicwall.com',
        'Lynn (Ling) Zhang [X] (Inactive)': 'hding@sonicwall.com',
        'Candy (Xiaolan) Chen [X] (Inactive)': 'hding@sonicwall.com',
        'Annie (Aidi) Liu': 'hding@sonicwall.com',
        'Hui (Hui) Ling': 'hling@sonicwall.com',
        'Jiancheng Pei': 'JPei@sonicwall.com',
        'Mario (Miao) Mao': 'mmao@sonicwall.com',
        'Zhong Chen': 'zchen@sonicwall.com',
        'Hui (Hui) Ling': 'hling@sonicwall.com',
        'Weily (Wei) Zhou': 'wzhou@sonicwall.com',
        'Fangyin Hu': 'FHu@sonicwall.com',
        'Spiller (Guolong) Zhu': 'gzhu@sonicwall.com',
        'June (Jianglan) Zhu': 'jzhu@sonicwall.com',
        'Eric (Dong) Xiang': 'exiang@sonicwall.com',
        'Tom (YiCheng) He': 'yhe@sonicwall.com',
        'Aaron (Bo) Zhang': 'azhang@sonicwall.com',
        'Tim (Yunfeng) Liu': 'yliu@sonicwall.com',
        'Yanjun Yang': 'yyang@sonicwall.com',
        'Lucia (Lulu) Wu': 'luwu@sonicwall.com',
        'Rickon (Xiaohua) Qin': 'rqin@sonicwall.com',
        'Tanner (Tieyun) Bao': 'tbao@sonicwall.com',
        'Martin (Qingbo) Gao': 'qgao@sonicwall.com',
        'Annie (Aidi) Liu': 'annieliu@sonicwall.com',
        'Gump (Lingjian) Gan': 'ggan@sonicwall.com',
        'Jian Zhang': 'jzhang@sonicwall.com',
        'Steven Yue': 'syue@sonicwall.com',
        'Thomas (Zixian) Tang': 'ztang@sonicwall.com',
        'Bruce (Riji) Cai': 'bcai@sonicwall.com',
        'Alex (Yixiu) Huang': 'ahuang@sonicwall.com',
        'Carl (Qing) Wang': 'qwang@sonicwall.com',
        'Crystal (Miao) Wei': 'cwei@sonicwall.com',
        'David (Wei) Li': 'dwli@sonicwall.com',
        'Dennis (Dehua) Qian': 'dqian@sonicwall.com',
        'Freeman (Longfei) Qin': 'FQin@sonicwall.com',
        'Grace (XiaoYan) Guo': 'xguo@sonicwall.com',
        'Stephen (Yan) Wang': 'yawang@sonicwall.com',
        'Tony (Yetong) Wang': 'ytwang@sonicwall.com',
        'Wenbo Wei': 'wwei@sonicwall.com',
        'Xingzhou Wang': 'XWang@sonicwall.com',
        'Yuan Wei': 'YuWei@sonicwall.com',
        'Zhiyong Huo': 'zhuo@sonicwall.com',
        'Zhiming Zhang': 'ZMZhang@sonicwall.com',
        'Shawndon (Xiaodong) Lin': 'sxlin@sonicwall.com',
        'Amber Shao': 'AShao@sonicwall.com',
        'Alan (LiangYa) Zhou': 'lzhou@sonicwall.com',
        'Desnyd (Yangqing) Hu': 'yahu@sonicwall.com',
        'Eric (Jin) Li': 'eli@sonicwall.com',
        'Garrison (Yusong) Gong': 'GGong@sonicwall.com',
        'Gary (Guo Hui) Zou': 'gzou@sonicwall.com',
        'Helen (Haiyan) Cui': 'hcui@sonicwall.com',
        'Jeremy (Lei) Zhou': 'JIZhou@sonicwall.com',
        'Jerry (XiaoJiang) Yang': 'xyang@sonicwall.com',
        'Jesse (Jie) Zhang': 'JJZhang@sonicwall.com',
        'Jiawei Wang': 'JWWang@sonicwall.com',
        'Jun Zhang': 'JnZhang@sonicwall.com',
        'Lesley (Laili) Wang': 'lawang@sonicwall.com',
        'Qi (Guanqi) Guan': 'qguan@sonicwall.com',
        'Yao Li': 'YaLi@sonicwall.com',
        'Ziqi Mao': 'ZMao@sonicwall.com',
        'David Huang': 'dahuang@sonicwall.com',
        'Albert Huang': 'ZHuang@sonicwall.com',
        'Alen (Yongquan) Xu': 'yoxu@sonicwall.com',
        'Bob (Yuhua) Yang': 'boyang@sonicwall.com',
        'Chris (MengXi) Wu': 'mwu@sonicwall.com',
        'Jay (Jie) Ma': 'jma@sonicwall.com',
        'Jowis (Guilin) Wu': 'gwu@sonicwall.com',
        'Maojun Jiang': 'MaJiang@sonicwall.com',
        'Mingming Jiang': 'MJiang@sonicwall.com',
        'Molly (Yangyang) Wang': 'MyWang@sonicwall.com',
        'Vivien (Qianqian) Chen': 'VChen@sonicwall.com',
        'Frank (Wei) Yao': 'wyao@sonicwall.com',
        'Xing Qu': 'SQu@sonicwall.com',
        'Yonglei Zhu': 'YZhu@sonicwall.com',
        'Yukii Zhou': 'YZhou@sonicwall.com',
        'Yonglei Hua': 'YHua@SonicWALL.com',
        'Conney (Xinchao) Peng': 'xpeng@SonicWall.com',
        'Celia (Xinyu) Zhan': 'xzhan@SonicWall.com',
        'Liguo Lu': 'llu@SonicWall.com',
        #                   'Annie (Aidi) Liu': 'annieliu@sonicwall.com',

        #                   'Eric (Dong) Xiang': 'exiang@sonicwall.com',
        #                   'Sophie Shi': 'sshi@sonicwall.com',
        #                   'Arun Yogeesh': 'ayogeesh@sonicwall.com',
        #                   'Tony (Yetong) Wang': 'ytwang@sonicwall.com',
        #                   'Weijie (Wei Jie) Shen': 'weshen@sonicwall.com',
        #                   'Wenbo Wei': 'wwei@sonicwall.com',
        #                   "Shane O'Hanlon" : 'sohanlon@sonicwall.com',
        #                   'Winni (Wenhua) Gu' : 'wgu@sonicwall.com',
        #                   'Weily (Wei) Zhou': 'wzhou@sonicwall.com',
        #                   'Zhong Chen': 'zchen@sonicwall.com',
        #                   'Saikiran Madugula': 'smadugula@sonicwall.com',
        #                   'Aaron (Bo) Zhang': 'azhang@sonicwall.com',
        #                   'Narayanan Ayyenperumal': 'nayyenperumal@sonicwall.com',
        #                   'Jenny (Jie) Liu': 'jliu@sonicwall.com',
        #                   'Mallikharjun Vatti': 'mvatti@sonicwall.com',
        #                   'Hui (Hui) Ling': 'hling@sonicwall.com',
        #                   'Sam Liddicott': 'sliddicott@sonicwall.com',
        #                   'Freeman (Longfei) Qin': 'fqin@sonicwall.com',
        #                   'Lucia (Lulu) Wu': 'luwu@sonicwall.com',
    }

    qa_2_mail_dict = {
        'Allen (Yaqiang) Nan': 'ynan@SonicWALL.com',
        'Emily (Yunzhu) Wei': 'ywei@SonicWALL.com',
        'Spring (Congli) Ye': 'coye@SonicWALL.com',
        'Kelly (Liyuan) Du': 'ldu@SonicWALL.com',
        'Sandy (Rong) Hu': 'rhu@SonicWALL.com',
        'Michelle (Xin) Ma': 'mma@SonicWALL.com',
        'Jie Lian': 'JLian@SonicWALL.com',
        'Jessie (Dan) Huang': 'dhuang@SonicWALL.com',
        'Emma  (Huihui) Xu': 'hxu@SonicWALL.com',
        'Emma (Huihui) Xu': 'hxu@SonicWALL.com',
        'Candy Chen': 'xchen@SonicWALL.com',
        'Cathy (Guimin) Zhao': 'czhao@SonicWALL.com',
        'Tracy (Juanjuan) Liu': 'juliu@SonicWALL.com',
        'Juanjuan Liu': 'juliu@SonicWALL.com',
        'Frank (Panjiang) Cao': 'pcao@SonicWALL.com',
        'Jun Zhang': 'JnZhang@SonicWALL.com',
        'Jack (Peining)  Zhou': 'pzhou@SonicWALL.com',
        'Jack (Peining) Zhou': 'pzhou@SonicWALL.com',
        'Alisa (Qiongling) Shi': 'qshi@SonicWALL.com',
        'Wei (Huawei) Hua': 'hhua@SonicWALL.com',
        'Bush (Yuhang) Chen': 'BYHChen@SonicWALL.com',
        'Jason (Kai) Huang': 'khuang@SonicWALL.com',
        'Caesar (Zhengrong) Ye': 'zye@SonicWALL.com',
        'Nick Zhang': 'NiZhang@SonicWALL.com',
        'XiangYun Zhou': 'XZhou@SonicWALL.com',
        'Chan Yuan': 'CYuan@SonicWALL.com',
        'Mike (Junhua) Wu': 'jwu@SonicWALL.com',
        'Mike (Junhua)  Wu': 'jwu@SonicWALL.com',
        'Xiuyun Hu': 'xhu@sonicwall.com',
        'Xuqian Yami Wang': 'xuwang@sonicwall.com',
        'Fitz Huang': 'fhuang@sonicwall.com',
        'Anna Ge': 'age@sonicwall.com',
        'Lebin Bian': 'lbian@SonicWALL.com',
        'Neil (Lei) Zhang': 'lezhang@SonicWALL.com',
        'Rosa  (RongXia) Meng': 'rmeng@SonicWALL.com',
        'Rosa (RongXia) Meng': 'rmeng@SonicWALL.com',
        'Yonglei Hua': 'YHua@SonicWALL.com',
        'Xinchao Peng': 'xpeng@SonicWall.com',
        'Liguo Lu': 'llu@SonicWall.com',
        'Celia (Xinyu) Zhan': 'xzhan@SonicWall.com',
        'Roger (Qinjie) Gu': 'qigu@sonicwall.com',
        'Lara (Lizhen) Wang': 'lwang@sonicwall.com',
    }

    system_mail_dict = {
        'Fangfang Xia': 'fxia@SonicWALL.com',
        'Jenny (Weijing) Huang': 'whuang@SonicWALL.com',
        'Judy (Yuan) Yuan': 'jyuan@SonicWALL.com',
        'Lucy Li': 'Luli@SonicWALL.com',
        'Si Li': 'luli@sonicwall.com',
        'Yuling Hou': 'YHou@SonicWALL.com',
        'Rock (Rufeng) Wei': 'rwei@SonicWALL.com',
        'Shawn (Jiran) Xiong': 'JRXiong@SonicWALL.com',
        'Stephanie Li': 'yili@SonicWALL.com',
        'Victor (Jianbo) Ding': 'vding@SonicWALL.com',
        'Xiaoren Xu': 'XXu@SonicWALL.com',
        'Lin Sun': 'LSun@SonicWALL.com',

    }

    qa_3_mail_dict = {
        'Wenlu Gong': 'wgong@SonicWALL.com',
        'Yaqian Ye': 'YYe@SonicWALL.com',
        'Chunxia Xu': 'cxu@SonicWALL.com',
        'Haoyuan Ma': 'HyMa@SonicWALL.com',
        'Joy Xu': 'JXu@SonicWALL.com',
        'Lily (Lili) Qian': 'lqian@SonicWALL.com',
        'Bruce (Yi) Chen': 'BYChen@SonicWALL.com',
        'Shang (Rongfang) Shang': 'rshang@SonicWALL.com',
        'Francis (Renbin) Lv': 'flv@sonicwall.com',
        'Chris (Feifei) Dai': 'cdai@sonicwall.com',

    }

    zhong_mail_dict = {
        'Hui (Hui) Ling': 'hling@sonicwall.com',
        'Jiancheng Pei': 'JPei@sonicwall.com',
        'Mario (Miao) Mao': 'mmao@sonicwall.com',
        'Zhong Chen': 'zchen@sonicwall.com',
        'Hui (Hui) Ling': 'hling@sonicwall.com',
        'Weily (Wei) Zhou': 'wzhou@sonicwall.com',
        'Fangyin Hu': 'FHu@sonicwall.com',
        'Spiller (Guolong) Zhu': 'gzhu@sonicwall.com',
    }

    eric_mail_dict = {
        'June (Jianglan) Zhu': 'jzhu@sonicwall.com',
        'Eric (Dong) Xiang': 'exiang@sonicwall.com',
        'Tom (YiCheng) He': 'yhe@sonicwall.com',
        'Aaron (Bo) Zhang': 'azhang@sonicwall.com',
        'Tim (Yunfeng) Liu': 'yliu@sonicwall.com',
        'Yanjun Yang': 'yyang@sonicwall.com',
        'Lucia (Lulu) Wu': 'luwu@sonicwall.com',
        'Rickon (Xiaohua) Qin': 'rqin@sonicwall.com',
        'Tanner (Tieyun) Bao': 'tbao@sonicwall.com',
        'Martin (Qingbo) Gao': 'qgao@sonicwall.com',
        'Annie (Aidi) Liu': 'annieliu@sonicwall.com',
        'Gump (Lingjian) Gan': 'ggan@sonicwall.com',
        'Jian Zhang': 'jzhang@sonicwall.com',
        'Steven Yue': 'syue@sonicwall.com',
        'Thomas (Zixian) Tang': 'ztang@sonicwall.com',

    }

    bruce_mail_dict = {
        'Bruce (Riji) Cai': 'bcai@sonicwall.com',
        'Alex (Yixiu) Huang': 'ahuang@sonicwall.com',
        'Carl (Qing) Wang': 'qwang@sonicwall.com',
        'Crystal (Miao) Wei': 'cwei@sonicwall.com',
        'David (Wei) Li': 'dwli@sonicwall.com',
        'Dennis (Dehua) Qian': 'dqian@sonicwall.com',
        'Freeman (Longfei) Qin': 'FQin@sonicwall.com',
        'Grace (XiaoYan) Guo': 'xguo@sonicwall.com',
        'Stephen (Yan) Wang': 'yawang@sonicwall.com',
        'Tony (Yetong) Wang': 'ytwang@sonicwall.com',
        'Wenbo Wei': 'wwei@sonicwall.com',
        'Xingzhou Wang': 'XWang@sonicwall.com',
        'Yuan Wei': 'YuWei@sonicwall.com',
        'Zhiyong Huo': 'zhuo@sonicwall.com',
        'Zhiming Zhang': 'ZMZhang@sonicwall.com',
    }

    shawndon_mail_dict = {
        'Shawndon (Xiaodong) Lin': 'sxlin@sonicwall.com',
        'Amber Shao': 'AShao@sonicwall.com',
        'Alan (LiangYa) Zhou': 'lzhou@sonicwall.com',
        'Desnyd (Yangqing) Hu': 'yahu@sonicwall.com',
        'Eric (Jin) Li': 'eli@sonicwall.com',
        'Garrison (Yusong) Gong': 'GGong@sonicwall.com',
        'Gary (Guo Hui) Zou': 'gzou@sonicwall.com',
        'Helen (Haiyan) Cui': 'hcui@sonicwall.com',
        'Jeremy (Lei) Zhou': 'JIZhou@sonicwall.com',
        'Jerry (XiaoJiang) Yang': 'xyang@sonicwall.com',
        'Jesse (Jie) Zhang': 'JJZhang@sonicwall.com',
        'Jiawei Wang': 'JWWang@sonicwall.com',
        'Jun Zhang': 'JnZhang@sonicwall.com',
        'Lesley (Laili) Wang': 'lawang@sonicwall.com',
        'Qi (Guanqi) Guan': 'qguan@sonicwall.com',
        'Yao Li': 'YaLi@sonicwall.com',
        'Ziqi Mao': 'ZMao@sonicwall.com',

    }

    david_mail_dict = {
        'David Huang': 'dahuang@sonicwall.com',
        'Albert Huang': 'ZHuang@sonicwall.com',
        'Alen (Yongquan) Xu': 'yoxu@sonicwall.com',
        'Bob (Yuhua) Yang': 'boyang@sonicwall.com',
        'Chris (MengXi) Wu': 'mwu@sonicwall.com',
        'Jay (Jie) Ma': 'jma@sonicwall.com',
        'Jowis (Guilin) Wu': 'gwu@sonicwall.com',
        'Maojun Jiang': 'MaJiang@sonicwall.com',
        'Mingming Jiang': 'MJiang@sonicwall.com',
        'Molly (Yangyang) Wang': 'MyWang@sonicwall.com',
        'Vivien (Qianqian) Chen': 'VChen@sonicwall.com',
        'Frank (Wei) Yao': 'wyao@sonicwall.com',
        'Xing Qu': 'SQu@sonicwall.com',
        'Yonglei Zhu': 'YZhu@sonicwall.com',
        'Yukii Zhou': 'YZhou@sonicwall.com',
    }
